### ISSUE TITLE
This parser plays poorly with Markdown

### ISSUE THREAD

**Issue by prometheas** [Whitebolt/shortcode-insert#12]
Given input like this:

```markdown
[block_quote][Linked text](https://github.com).[/block_quote]
```

And a shortcode definition:

```js
renderer.add('block_quote', (atts, content) => {
  return `<blockquote>${content}</blockquote>`;
});
```

The library will output:

```html
<blockquote>[!Linked text!](https://github.com).</blockquote>
```

It'd be nice to have a config option to suppress the mutation of text in square brackets when there is no match with a defined shortcode name.

**Comment by ssimpo** [comment]
Thanks for your suggestion.

Actually, it already does this. Perhaps I have missed something in your question?

Here is an example that works:

```javascript
const Shortcode = require('shortcode-insert');

const parser = Shortcode({
    start: '[',
    end: ']'
});

parser.add('block_quote', tag=>`<blockquote>${tag.content}</blockquote>`);
```

I noticed you are using *wordpress style* shortcodes (single bracket) so I have copied that in my example.  The error you were getting might have been because of this line?

```javascript
renderer.add('block_quote', (atts, content) => {
```

The parser only passes one parameter to the function, content is a property of that object.  So, this is correct:

```javascript
renderer.add('block_quote', (tag) => {
```

Tag has a series of properties:

* **tagName:** *string*  Name of the tag.
* **endTag:** *boolean*  Is this a closing tag? Not normally true unless self-closing.
* **fullMatch** *string*  The full tag content, including the delimiters and opening and closing tags and content.
* **tagContents** *string*  The contents of the opening tag (this is the tag name and attributes astext not the content between any opening and closing tags).
* **start** *integer*  The start position in the string being parsed for this tag.
* **end** *integer*  The end position for this tag in the string being parsed (this is the final closing point of tag at end of any closing tag).
* **content** *string*  The tag contents (between the opening and closing tags).  Will be empty string if self-closing.
* **attributes** *Object*  Object containing all the tag attributes as key/value pairs.  Will also index attributes as numbered items, so you can reference the order of attributes too.  Attributes without a key and value can be referenced via the numbered items. This means you can parse attributes according to position as well as property name.

It could also be that this github repo has a slightly newer version of the library than published to npmjs.  To be sure I've added a test for your example, bumped the version and published to npmjs.

**Comment by ssimpo** [comment]
We are closing this issue now as far as we can tell it wasn't actually an issue.

If you are still having problems and/or the above does not help; please feel free to post back here or open new bug.
